---

 - name: talk to all hosts just so we can learn about them
   hosts: all
   tasks:   
   
     - name: create PSK
       shell: openssl rand -hex 32 > /etc/zabbix/psk.psk | cat /etc/zabbix/psk.psk
       register: command_psk
     - name: download new config
       shell: curl https://raw.githubusercontent.com/ITC-jwaltenspuehl/ansible-zabbix-install-proxy/main/zabbix_proxy.conf --output /etc/zabbix/zabbix_proxy.conf
       register: command_config
     - name: restart zabbix services
       shell: systemctl restart zabbix-proxy
       register: command_restart
       
     - debug:
                   var: command_psk.stdout_lines
     - debug:
                   var: command_config.stdout_lines
     - debug:
                   var: command_restart.stdout_lines
