---

 - name: talk to all hosts just so we can learn about them
   hosts: all
   tasks:
     - name: Import a key from a url
       ansible.builtin.rpm_key:
       state: present
       key: https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-A14FE591
     - name: install Zabbix Repo
       yum:
         name: https://repo.zabbix.com/zabbix/6.0/rhel/9/x86_64/zabbix-release-6.0-4.el9.noarch.rpm
         state: present
     - name: install Zabbix Repo
       yum:
         name: zabbix-proxy-sqlite
         state: latest
     - name: remove default config
       command: rm -f /etc/zabbix/zabbix-proxy.conf
